/**
 * 导出管理器
 * 负责将识别结果导出为各种格式
 */

import type { RecognizedFormula } from './RecognitionEngine';

/**
 * 导出格式
 */
export type ExportFormat = 'latex' | 'markdown' | 'json' | 'text';

/**
 * 导出选项
 */
export interface ExportOptions {
  /** 是否包含元数据 */
  includeMetadata?: boolean;
  /** 是否包含失败的识别 */
  includeFailures?: boolean;
  /** 是否按页面分组 */
  groupByPage?: boolean;
  /** 是否添加注释 */
  addComments?: boolean;
  /** 文档标题 */
  documentTitle?: string;
}

/**
 * 导出管理器
 */
export class ExportManager {
  /**
   * 导出为LaTeX文档
   * 
   * @param formulas - 识别结果数组
   * @param options - 导出选项
   * @returns LaTeX文档内容
   */
  exportAsLatex(formulas: RecognizedFormula[], options: ExportOptions = {}): string {
    const lines: string[] = [];

    // 文档头部
    lines.push('% LaTeX Document - Exported from Formula OCR');
    lines.push(`% Generated: ${new Date().toISOString()}`);
    lines.push(`% Total Formulas: ${formulas.length}`);
    lines.push('');
    lines.push('\\documentclass{article}');
    lines.push('\\usepackage{amsmath}');
    lines.push('\\usepackage{amssymb}');
    lines.push('\\usepackage{amsfonts}');
    lines.push('');

    if (options.documentTitle) {
      lines.push(`\\title{${options.documentTitle}}`);
      lines.push('\\author{Formula OCR}');
      lines.push(`\\date{${new Date().toLocaleDateString()}}`);
      lines.push('');
    }

    lines.push('\\begin{document}');
    lines.push('');

    if (options.documentTitle) {
      lines.push('\\maketitle');
      lines.push('');
    }

    // 过滤公式
    const validFormulas = options.includeFailures
      ? formulas
      : formulas.filter((f) => f.recognitionSuccess);

    // 按页面分组
    if (options.groupByPage) {
      const groupedByPage = this.groupFormulasByPage(validFormulas);

      for (const [pageNumber, pageFormulas] of groupedByPage.entries()) {
        lines.push(`\\section*{Page ${pageNumber}}`);
        lines.push('');

        pageFormulas.forEach((formula, index) => {
          this.addFormulaToLatex(lines, formula, index + 1, options);
        });

        lines.push('');
      }
    } else {
      // 不分组，按顺序输出
      validFormulas.forEach((formula, index) => {
        this.addFormulaToLatex(lines, formula, index + 1, options);
      });
    }

    lines.push('\\end{document}');

    return lines.join('\n');
  }

  /**
   * 导出为Markdown文档
   * 
   * @param formulas - 识别结果数组
   * @param options - 导出选项
   * @returns Markdown文档内容
   */
  exportAsMarkdown(formulas: RecognizedFormula[], options: ExportOptions = {}): string {
    const lines: string[] = [];

    // 文档头部
    lines.push(`# ${options.documentTitle || 'Exported Formulas'}`);
    lines.push('');
    lines.push(`> Generated by Formula OCR on ${new Date().toLocaleString()}`);
    lines.push(`> Total Formulas: ${formulas.length}`);
    lines.push('');

    // 过滤公式
    const validFormulas = options.includeFailures
      ? formulas
      : formulas.filter((f) => f.recognitionSuccess);

    // 按页面分组
    if (options.groupByPage) {
      const groupedByPage = this.groupFormulasByPage(validFormulas);

      for (const [pageNumber, pageFormulas] of groupedByPage.entries()) {
        lines.push(`## Page ${pageNumber}`);
        lines.push('');

        pageFormulas.forEach((formula, index) => {
          this.addFormulaToMarkdown(lines, formula, index + 1, options);
        });

        lines.push('');
      }
    } else {
      // 不分组，按顺序输出
      validFormulas.forEach((formula, index) => {
        this.addFormulaToMarkdown(lines, formula, index + 1, options);
      });
    }

    return lines.join('\n');
  }

  /**
   * 导出为纯文本
   * 
   * @param formulas - 识别结果数组
   * @param options - 导出选项
   * @returns 纯文本内容
   */
  exportAsText(formulas: RecognizedFormula[], options: ExportOptions = {}): string {
    const lines: string[] = [];

    lines.push('Exported Formulas - Formula OCR');
    lines.push(`Generated: ${new Date().toLocaleString()}`);
    lines.push(`Total Formulas: ${formulas.length}`);
    lines.push('');
    lines.push('='.repeat(60));
    lines.push('');

    const validFormulas = options.includeFailures
      ? formulas
      : formulas.filter((f) => f.recognitionSuccess);

    validFormulas.forEach((formula, index) => {
      lines.push(`Formula ${index + 1}`);
      lines.push(`Page: ${formula.pageNumber}`);
      lines.push(`Type: ${formula.type}`);
      lines.push(`Position: (${formula.boundingBox.x}, ${formula.boundingBox.y})`);

      if (formula.recognitionSuccess) {
        lines.push('LaTeX:');
        lines.push(formula.latexContent);
      } else {
        lines.push(`Error: ${formula.recognitionError || 'Recognition failed'}`);
      }

      lines.push('');
      lines.push('-'.repeat(60));
      lines.push('');
    });

    return lines.join('\n');
  }

  /**
   * 导出为JSON
   * 
   * @param formulas - 识别结果数组
   * @param options - 导出选项
   * @returns JSON字符串
   */
  exportAsJson(formulas: RecognizedFormula[], options: ExportOptions = {}): string {
    const validFormulas = options.includeFailures
      ? formulas
      : formulas.filter((f) => f.recognitionSuccess);

    const exportData = {
      metadata: {
        exportDate: new Date().toISOString(),
        totalFormulas: validFormulas.length,
        generator: 'Formula OCR System',
        version: '2.0',
      },
      formulas: validFormulas.map((formula) => ({
        id: formula.id,
        pageNumber: formula.pageNumber,
        type: formula.type,
        boundingBox: formula.boundingBox,
        latexContent: formula.latexContent,
        markdownContent: formula.markdownContent,
        recognitionSuccess: formula.recognitionSuccess,
        recognitionError: formula.recognitionError,
        confidence: formula.confidence,
        ...(options.includeMetadata && {
          metadata: formula.metadata,
          recognitionTime: formula.recognitionTime,
        }),
      })),
    };

    return JSON.stringify(exportData, null, 2);
  }

  /**
   * 下载文件
   * 
   * @param content - 文件内容
   * @param filename - 文件名
   * @param format - 文件格式
   */
  downloadFile(content: string, filename: string, format: ExportFormat): void {
    const mimeTypes: Record<ExportFormat, string> = {
      latex: 'text/x-latex',
      markdown: 'text/markdown',
      json: 'application/json',
      text: 'text/plain',
    };

    const extensions: Record<ExportFormat, string> = {
      latex: 'tex',
      markdown: 'md',
      json: 'json',
      text: 'txt',
    };

    const blob = new Blob([content], { type: mimeTypes[format] });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');

    link.href = url;
    link.download = `${filename}.${extensions[format]}`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    // 清理URL对象
    setTimeout(() => URL.revokeObjectURL(url), 100);
  }

  /**
   * 添加公式到LaTeX文档
   */
  private addFormulaToLatex(
    lines: string[],
    formula: RecognizedFormula,
    index: number,
    options: ExportOptions
  ): void {
    if (options.addComments) {
      lines.push(`% Formula ${index} - Page ${formula.pageNumber}`);
      lines.push(`% Type: ${formula.type}, Confidence: ${(formula.confidence * 100).toFixed(1)}%`);
    }

    if (!formula.recognitionSuccess) {
      lines.push(`% ERROR: ${formula.recognitionError || 'Recognition failed'}`);
      lines.push('');
      return;
    }

    // 根据公式类型选择环境
    if (formula.type === 'display' || formula.type === 'numbered') {
      lines.push('\\begin{equation}');
      lines.push(`  ${formula.latexContent}`);
      lines.push('\\end{equation}');
    } else {
      lines.push(`$${formula.latexContent}$`);
    }

    lines.push('');
  }

  /**
   * 添加公式到Markdown文档
   */
  private addFormulaToMarkdown(
    lines: string[],
    formula: RecognizedFormula,
    index: number,
    options: ExportOptions
  ): void {
    if (options.addComments) {
      lines.push(`<!-- Formula ${index} - Page ${formula.pageNumber} -->`);
      lines.push(`<!-- Type: ${formula.type}, Confidence: ${(formula.confidence * 100).toFixed(1)}% -->`);
    }

    if (!formula.recognitionSuccess) {
      lines.push(`> **Error**: ${formula.recognitionError || 'Recognition failed'}`);
      lines.push('');
      return;
    }

    lines.push(formula.markdownContent);
    lines.push('');
  }

  /**
   * 按页面分组公式
   */
  private groupFormulasByPage(
    formulas: RecognizedFormula[]
  ): Map<number, RecognizedFormula[]> {
    const grouped = new Map<number, RecognizedFormula[]>();

    for (const formula of formulas) {
      const pageFormulas = grouped.get(formula.pageNumber) || [];
      pageFormulas.push(formula);
      grouped.set(formula.pageNumber, pageFormulas);
    }

    // 按页面内位置排序
    for (const [, pageFormulas] of grouped) {
      pageFormulas.sort((a, b) => {
        // 先按Y坐标排序（从上到下）
        if (Math.abs(a.boundingBox.y - b.boundingBox.y) > 20) {
          return a.boundingBox.y - b.boundingBox.y;
        }
        // 同一行按X坐标排序（从左到右）
        return a.boundingBox.x - b.boundingBox.x;
      });
    }

    return grouped;
  }
}
